# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TODO' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TODO
	pod 'RxSwift', '~> 4.0'
	pod 'RxCocoa', '~> 4.0'

end
